name: grocery_list_app
description: A simple grocery list app using Flutter and BLoC pattern.

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.7.0
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  shared_preferences: ^2.2.3
  uuid: ^4.4.2
  flutter_test:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.3.0
  json_serializable: ^6.5.0
environment:
  sdk: '^3.4.0'
flutter:
  uses-material-design: true